# Copyright (c) 2020, XMOS Ltd, All rights reserved
import os, subprocess

def recursive(context, command):
    root = os.getcwd()
    print('Searching subdirectories of %s' % context.path.abspath())
    for dir_name, subdir_list, file_list in os.walk(root):
        absolute = os.path.abspath(dir_name)
        if absolute == root:
            continue
        relative = os.path.abspath(dir_name)[len(root) + 1:]
        if 'wscript' in file_list:
            print('Moving to subdirectory %s' % relative)
            os.chdir(absolute)
            subprocess.check_call(['waf', command])
    os.chdir(root)

def configure(conf):
    recursive(conf, 'configure')

def build(bld):
    if bld.cmd == 'build':
        recursive(bld, 'build')
    elif bld.cmd == 'clean':
        recursive(bld, 'clean')
