# Copyright (c) 2019, XMOS Ltd, All rights reserved
import os, shutil

def options(opt):
    opt.load('xwaf.xcommon')

def configure(conf):
    conf.load('xwaf.xcommon')    
    conf.env.PROJECT_ROOT = '../../../..'

def build(bld):
    makefile_opts = {
        'TARGET': ['XCORE-200-EXPLORER'],
        'XCC_FLAGS': ['-O2', '-g', '-Wall'],
        'USED_MODULES': ['lib_dfu', 'lib_xassert', 'lib_logging'],
        'XCOMMON_MAKEFILE': ['Makefile.common']
    }
    bld.do_xcommon(makefile_opts)
    if bld.cmd == 'clean':
        try:
            shutil.rmtree('bin')
        except OSError:
            pass
