# Copyright (c) 2019-2020, XMOS Ltd, All rights reserved
import shutil

def options(opt):
    opt.load('xwaf.xcommon')

def configure(conf):
    conf.load('xwaf.xcommon')
    conf.env.PROJECT_ROOT = '../../../../..'

def build(bld):
    makefile_opts = {
        'TARGET': ['XCORE-200-EXPLORER'],
        'XCC_FLAGS': ['-O2', '-g', '-Wall', '-fcmdline-buffer-bytes=256',
                      '-DQUADFLASH_DATA_PARTITION_UNIT_TEST'],
        'INCLUDE_DIRS': ['../../../../../lib_flash_data_partition/lib_flash_data_partition/src'],
        'USED_MODULES': ['lib_dfu', 'lib_xassert', 'lib_logging'],
        'XCOMMON_MAKEFILE': ['Makefile.common']
    }
    bld.do_xcommon(makefile_opts)
    if bld.cmd == 'clean':
        try:
            shutil.rmtree('bin')
        except OSError:
            pass
