# Copyright (c) 2020, XMOS Ltd, All rights reserved
import shutil

def options(opt):
    opt.load('xwaf.xcommon')

def configure(conf):
    conf.load('xwaf.xcommon')
    conf.env.PROJECT_ROOT = '../../../../..'

def build(bld):
    makefile_opts = {
        'TARGET': ['XCORE-200-EXPLORER'],
        'XCC_FLAGS': ['-O2', '-g', '-Wall', '-lsqiaccess', '-lquadspi',
                      '-fcmdline-buffer-bytes=256'],
        'INCLUDE_DIRS': ['../../../../boot'],
        'USED_MODULES': ['lib_xassert', 'lib_logging'],
        'XCOMMON_MAKEFILE': ['Makefile.common']
    }
    bld.do_xcommon(makefile_opts)
    if bld.cmd == 'clean':
        try:
            shutil.rmtree('bin')
        except OSError:
            pass
