#ifndef DFU_HOST_COMMANDS_H
#define DFU_HOST_COMMANDS_H

#include "dfu_commands.h"
#include "dfu_types.h"

#define DFU_CMD_DETACH DFU_DETACH
#define DFU_CMD_BUS_RESET XMOS_BUS_RESET
#define DFU_CMD_DNLOAD DFU_DNLOAD
#define DFU_CMD_CLRSTATUS DFU_CLRSTATUS
#define DFU_CMD_REBOOT XMOS_REBOOT
#define DFU_CMD_GETSTATE DFU_GETSTATE
#define DFU_CMD_GETSTATUS DFU_GETSTATUS
#define DFU_CMD_GET_ERROR_INFO XMOS_GET_ERROR_INFO

#endif
